### ISSUE TITLE
Data folder

### ISSUE THREAD

**Issue by ogola89** [PacktPublishing/Hands-On-Data-Science-for-Marketing#2]
Hi There,

Both in Github and on packt the data files are missing. Do you have a folder where these are, rather than having to download each of them and place them in the right folders relative to the notebooks?

Thanks

**Comment by packt-pradeeps** [comment]
No, you'll have to download the data files separately

**Comment by claudiaregio** [comment]
I also came here to file a bug because the data was missing - I'm genuinely shocked this issue appears to be closed as designed. Did no one think it would be a huge pain point for people going through the book to attempt to find the same data sources that the author uses, download them separately and rename them to match what is in the notebook and place it in the appropriate folder?
